version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  back:
    build: .
    command: sh -c "python3 manage.py migrate && gunicorn task_level.wsgi:application --workers 2 --bind 0.0.0.0:8000 "
    restart: always
    volumes:
      - ../static/:/code/static/
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
    volumes:
      - ./django_static/:/usr/share/nginx/html/django_static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:

