# Generated by Django 4.1.4 on 2022-12-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('create_date_time', models.DateTimeField()),
                ('finish_date_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField(choices=[(0, ''), (1, 'Low'), (2, 'Moderate'), (3, 'High')], default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='task_level_app.status')),
            ],
            options={
                'ordering': ['-create_date_time'],
            },
        ),
    ]
