# Generated by Django 4.1.4 on 2022-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_level_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
