# Generated by Django 4.1.4 on 2022-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_level_app', '0002_alter_task_create_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
